auth_enabled: false
server:
  http_listen_port: 3100
distributor:
  ring:
    kvstore:
      store: inmemory
common:
  path_prefix: /loki  # Resolves compactor working_directory issue
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory   
schema_config:
  configs:
#    - from: 2020-01-01
#      store: boltdb-shipper
    - from: 2023-01-01  # Updated start date
      store: tsdb
      object_store: filesystem
#      schema: v11
      schema: v13       # Updated to v13
      index:
        prefix: index_
        period: 24h
        
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
#    shared_store: filesystem
  filesystem:
    directory: /loki/chunks
    
limits_config:
  max_query_series: 10000
  allow_structured_metadata: true  # Enable OTLP ingestion support