scrape_configs:
  - job_name: 'monitoring-apps'
    scrape_interval: 5s
    static_configs:
      - targets: ['demo-web-api:80', 'demo-web-app:80'] #for production test
#      - targets: ['host.docker.internal:5001', 'host.docker.internal:5002'] #for local test
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
